### ISSUE TITLE
Introduce exponential back off for rate-limited API calls

### ISSUE THREAD

**Issue by dgreene-r7** [rapid7/builderator#117]
Builderator can fail builds if it receives a rate-limited exception while checking an AMI's copy status. We need to catch these exceptions and follow Amazon's recommendation of introducing exponential back off before retrying.

**Comment by athompson-r7** [comment]
@dgreene-r7 Backoff on `describe_images` was added in #107, are there more apis that need this?

**Comment by dgreene-r7** [comment]
Nope! We just need to update the version our jobs are using. Derp!
