### ISSUE TITLE
autoversion.create_tags docs inconsistent with defaults

### ISSUE THREAD

**Issue by athompson-r7** [rapid7/builderator#56]
Documentation and code defaults for `autoversion.create_tags` are inconsistent.  I'm not sure which is right.

https://github.com/rapid7/builderator/blob/master/lib/builderator/config/defaults.rb#L16
and 
https://github.com/rapid7/builderator/blob/master/docs/versioning.md#configuration

**Comment by erran-r7** [comment]
@athompson-r7 looks like @jmanero-r7 updated the default in https://github.com/rapid7/builderator/commit/fd072540fc4405bd16d663b1575b4b78823c7953 without adjusting the documentation.
